In [ ]:
import pandas as pd
import numpy as np

financialinclusion=pd.read_csv("Financial_inclusion_dataset.csv")
financialinclusion.head()

country                   0
year                      0
uniqueid                  0
bank_account              0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64

In [4]:
financialinclusion.isnull().sum()

country                   0
year                      0
uniqueid                  0
bank_account              0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64

In [5]:
financialinclusion.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [7]:
new_columns=['bank_account','location_type','age_of_respondent','education_level','job_type']
financialinclusion=financialinclusion.drop([c for c in financialinclusion.columns if c not in new_columns],axis=1)
financialinclusion.head()

,bank_account,location_type,age_of_respondent,education_level,job_type
0,Yes,Rural,24,Secondary education,Self employed
1,No,Rural,70,No formal education,Government Dependent
2,Yes,Urban,26,Vocational/Specialised training,Self employed
3,No,Rural,34,Primary education,Formally employed Private
4,No,Urban,26,Primary education,Informally employed

In [9]:
import os
data=financialinclusion
df=pd.DataFrame(data)
csv_filename="cleaned_financialinclusion.csv"
df.to_csv(csv_filename, index=False)
print(f"Success! '{csv_filename}' has been created in: {os.getcwd()}")

Success! 'cleaned_financialinclusion.csv' has been created in: c:\Users\MSI\Downloads\ML-For-Beginners-main (1)\Capstone\FinTwin-ai\Uncleaned Data